### ISSUE TITLE
Allow users to register callbacks for specific browser / tab events

### ISSUE THREAD

**Issue by Dowwie** [atroche/rust-headless-chrome#106]
wait_until_X logic ought to be used for edge cases rather than the standard for this library.  Instead, callbacks should be registered and called when certain events are triggered by chrome.  For instance, when loadEventFired is sent by chrome, call print_to_pdf(..).

**Comment by atroche** [comment]
I agree that it would be good to allow adding callbacks for various events. It hasn't come up in my work yet, so I haven't put any thought into designing an API for it.

That being said, while I'm open to have an alternative fully-asynchronous API, I prefer using the synchronous one, because otherwise you end up with browser tests with a fair bit of boilerplate in them, like all the `and_then`s in [this example from fantoccini](https://github.com/jonhoo/fantoccini#examples).

Is it okay if I change the title of this issue to "Allow users to add callbacks for specific browser / tab events"? Or, if it's more what you're after, "implement asynchronous API"?

Interestingly, `fantoccini` has an inverse issue: https://github.com/jonhoo/fantoccini/issues/43

**Comment by Dowwie** [comment]
@atroche I agree with your recommended title change, although a fully async api would also be great.

**Comment by jianglibo** [comment]
callbacks? I cannot find term callback in Tokio, but Futures. I tried all and_thens, skip_whiles all of them end with messes. When I stop use these future combinators and implement own futures, things begin to look easier. Think of Browser as a source of raw messages(all message) of a stream. then Page as a more specific message source, finally your own page which consumes Page stream, and sends method to.  You should start writing code as Tokio way, starting off with a future. the code below demonstrates this idea:
```rust
impl Future for MyPage {
    type Item = ();
    type Error = failure::Error;

    fn poll(&mut self) -> Poll<(), Self::Error> {
        loop {
            if let Some(value) = try_ready!(self.chrome_page.poll()) {
                    match &mut self.state {
                        MyPageState::Start => {
                            info!("*** Start ***");
                            if let PageMessage::DocumentAvailable = value {
                                self.state = MyPageState::WaitingNode;
                                self.chrome_page.find_node(self.node_id);
                            }
                        }
                        MyPageState::WaitingNode => {
                            info!("*** WaitingNode ***");
                            if let PageMessage::FindNode(maybe_selector, nd) = value {
                                if Some(self.node_id.to_string()) == maybe_selector {
                                    info!("got node {:?}", nd);
                                    self.state = MyPageState::WaitElement;
                                }
                            }
                        }
                        MyPageState::WaitElement => {
                            info!("*** WaitingElement ***");
                            if let PageMessage::FindElement(selector, element) = value {
                                if self.node_id == &selector {
                                    info!("got element {:?}", element);
                                    self.state = MyPageState::WaitingScreenshot;
                                    self.chrome_page.capture_screenshot(page::ScreenshotFormat::JPEG(Some(100)),
                                        None,
                                        true
                                    )
                                }
                            }
                        }
                        MyPageState::WaitingScreenshot => {
                            info!("*** WaitingScreenshot ***");
                            if let PageMessage::Screenshot(jpeg_data) = value {
                                self.state = MyPageState::Consuming;
                                fs::write("screenshot.jpg", &jpeg_data).unwrap();
                            }
                        }
                        _ => {
                            trace!("receive message: {:?}", value);
                        },
                    }
                } else {
                    error!("got None, was stream ended?");
                }
            }
    }
}
```

**Comment by Dowwie** [comment]
Hi @jianglibo! Welcome to the discussion.  "Callback" is a common design pattern where one event triggers the call of others (they're "called back").  Should @atroche decide to turn the entire headless-chrome library asynchronous, then a Future such as what you've described could be considered.  

I think that it is worth moving to an asyncio design.  headless-chrome's operations would benefit by maximizing concurrency enabled by Futures, and an async-await api for headless chrome is really great.  (see pyppeteer lib for instance)

**Comment by jianglibo** [comment]
@Dowwie I agree callback is a common design pattern. But the Tokio is some how different, which drive your code to run in a uniqe way. I now know how to make stucked poll loop to keep looping. The async version of take screenshot is as below:
```rust
                match value {
                    PageMessage::DocumentAvailable => {
                        self.chrome_page.one_page.capture_screenshot_by_selector("#login", page::ScreenshotFormat::JPEG(Some(100)), true);
                    }
                    PageMessage::Screenshot(selector,_, _, jpeg_data) => {
                        fs::write("screenshot.jpg", &jpeg_data.unwrap()).unwrap();
                    }
                    _ => {
                        info!("got unused page message {:?}", value);
                    }
                }
```
I didn't know why sometimes I could'nt get "Page.loadEventFired". When this happened, the whole app would stucked, Because you don't send commands to chrome, chrome return no more messages, it's locked, in sync code you can solve this problem by timeout, but under tokio the way to restart a stucked future is a new event source which will notify tokio to poll your code again, like the interval. All these code is here:  [https://github.com/jianglibo/rust-headless-chrome/tree/master/src/browser_async](https://github.com/jianglibo/rust-headless-chrome/tree/master/src/browser_async). Maybe I understood tokio wrongly, Any help is appreciated. My english skill is a problem to expression the idea clearly.
