### ISSUE TITLE
adding an option to add sleeps between tab actions

### ISSUE THREAD

**Issue by mlleprudhomme** [atroche/rust-headless-chrome#171]
hello,

I've been doing some testing, and my human eyes cannot follow the actions being taken in the browser.

I've been adding in sleeps between each action and then removing them once I'm satisfied with the behaviour. I figure if I'm doing this, other people are as well, so it might be worth adding an option.

Thoughts? 
🐻

**Comment by atroche** [comment]
Yeah, good idea! I've had the same itch. PR very welcome :)

I think Puppeteer has a `slowMo` option. I'd be curious to find out which things they add a delay after. 

Presumably they do add the delay after clicking, but not querying the DOM. But what about stuff like moving the mouse?

Oh, okay, after a quick look [it seems](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Connection.js#L93-L95) like they add a delay for literally every message sent to the browser. I guess that'd work as a first pass ;)

Big question for me is whether it's really something to add to `LaunchOptions`, or to the `Browser` constructor itself... My gut says latter, although that'd complicate implementation a bit.

What do you think?

**Comment by atroche** [comment]
Maybe it could be a "slowMoFactor" rather than an absolute number of milliseconds. I know that personally I'd prefer to eg wait longer after a click, but not as long after a keypress (I mean, if you're typing an email and password into a login form, do you really want to wait 100ms after each letter? But I can imagine wanting to wait 100ms or even longer after doing various clicks.)

So if the option is a "factor" or "multiplier" (which defaults to 0) then inside click we can have something like sleep(multiplier * 100ms) but inside press_key sleep(multiplier * 10ms).
