### ISSUE TITLE
Figure out why `capture_screenshot` test fails on my MacBook but not on Travis

### ISSUE THREAD

**Issue by atroche** [atroche/rust-headless-chrome#55]
Currently on master it panics:

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/29839/52931055-0e0c1400-339f-11e9-86ed-63c14b468274.png">

And when I use `u32`s instead of `u16`s I find that the `err` from here: https://github.com/atroche/rust-headless-chrome/blob/f39ddf2bc7fe3d30dc420867504e8a8a2857e2ce/tests/simple.rs#L81-L86

is `147101`.

Chrome 72, Mac OS 10.14.3. I tried doing `cargo clean` and got the same result.

**Comment by atroche** [comment]
cc @lukaslueg

**Comment by lukaslueg** [comment]
The test fails because the resulting screenshot is just 1x1 pixels of a different color. The culprit is `from_surface` which if set to `Some(false)` (screenshot is taken from the `View` rather than the `Surface`) causes this behavior. But only on MacOS it seems.

I don't know what chrome means with `View` and `Surface` but I guess I'd be fine to just change the test. I'll fix that later.
